# Exercise real executables as well as the stream-based CLI unit boundary.
set(fixture "${TEST_DIR}/cli-process.parquet")
file(REMOVE "${fixture}")
execute_process(COMMAND "${FIXTURE_TOOL}" "${fixture}" 23 7 RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Fixture generator failed: ${result}")
endif()
execute_process(COMMAND "${QUANTA}" version RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 0 OR NOT output MATCHES "Quanta 0.1.0")
  message(FATAL_ERROR "version failed: ${result}: ${output}")
endif()
execute_process(COMMAND "${QUANTA}" inspect "${fixture}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 0 OR NOT output MATCHES "Row groups: 4")
  message(FATAL_ERROR "inspect failed: ${result}: ${output}")
endif()
execute_process(COMMAND "${QUANTA}" scan "${fixture}" --columns name,id --batch-size 4 --limit 5
  RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 0 OR NOT output MATCHES "Displayed 5 rows from 2 batches")
  message(FATAL_ERROR "scan failed: ${result}: ${output}")
endif()
execute_process(COMMAND "${QUANTA}" scan "${fixture}" --columns missing
  RESULT_VARIABLE result ERROR_VARIABLE error OUTPUT_QUIET)
if(NOT result EQUAL 1 OR NOT error MATCHES "missing")
  message(FATAL_ERROR "Invalid projection returned ${result}: ${error}")
endif()
execute_process(COMMAND "${FIXTURE_TOOL}" "${fixture}" RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 1 OR NOT error MATCHES "Refusing to overwrite")
  message(FATAL_ERROR "Fixture overwrite protection failed: ${result}: ${error}")
endif()
file(REMOVE "${fixture}")
