function(quanta_target_options target)
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror)
    if(QUANTA_ENABLE_ASAN)
      target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
      target_link_options(${target} PUBLIC -fsanitize=address)
    endif()
    if(QUANTA_ENABLE_UBSAN)
      target_compile_options(${target} PRIVATE -fsanitize=undefined -fno-sanitize-recover=undefined -fno-omit-frame-pointer)
      target_link_options(${target} PUBLIC -fsanitize=undefined -fno-sanitize-recover=undefined)
    endif()
  elseif(QUANTA_ENABLE_ASAN OR QUANTA_ENABLE_UBSAN)
    message(FATAL_ERROR "Sanitizer options require Clang or GCC")
  endif()
endfunction()
